include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/models/models.g.dart
    - 'lib/**/**.freezed.dart'
    - 'lib/**/**.g.dart'
    - 'example/**/*.dart'
  errors:
    missing_required_param: warning
    missing_return: warning
linter:
  rules:
